<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_0507 [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (0507)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT 0507 (lh)>
	<!ATTLIST 0507 id NMTOKEN #REQUIRED>
	<!ATTLIST 0507 expanded NMTOKEN #REQUIRED>
	<!ELEMENT lh (distal_cluster)>
	<!ATTLIST lh id NMTOKEN #REQUIRED>
	<!ATTLIST lh expanded NMTOKEN #REQUIRED>
	<!ELEMENT distal_cluster (axon, ddt, synapse)>
	<!ATTLIST distal_cluster id NMTOKEN #REQUIRED>
	<!ATTLIST distal_cluster expanded NMTOKEN #REQUIRED>
	<!ELEMENT axon (area_list)>
	<!ATTLIST axon id NMTOKEN #REQUIRED>
	<!ATTLIST axon expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT ddt (area_list)>
	<!ATTLIST ddt id NMTOKEN #REQUIRED>
	<!ATTLIST ddt expanded NMTOKEN #REQUIRED>
	<!ELEMENT synapse (profile_list)>
	<!ATTLIST synapse id NMTOKEN #REQUIRED>
	<!ATTLIST synapse expanded NMTOKEN #REQUIRED>
	<!ELEMENT profile_list (profile)>
	<!ATTLIST profile_list id NMTOKEN #REQUIRED>
	<!ATTLIST profile_list oid NMTOKEN #REQUIRED>
	<!ATTLIST profile_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT profile EMPTY>
	<!ATTLIST profile id NMTOKEN #REQUIRED>
	<!ATTLIST profile oid NMTOKEN #REQUIRED>
	<!ATTLIST profile expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Project"
		unuid="1274431451580.1187161872.1249385082"
		mipmaps_folder="trakem2.1274431451580.1187161872.1249385082/trakem2.mipmaps/"
		storage_folder=""
		mipmaps_format="0"
	>
	</project>
	<t2_layer_set
		oid="12"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="4008.0"
		layer_height="2672.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		n_layers_color_cue="-1"
		paint_arrows="true"
		paint_edge_confidence_boxes="true"
	>
		<t2_calibration
			pixelWidth="1.0"
			pixelHeight="1.0"
			pixelDepth="1.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="pixel"
		/>
		<t2_layer oid="14"
			 thickness="1.0"
			 z="0.0"
			 title=""
		>
			<t2_patch
				oid="72"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 j5-6.bmp"
				links=""
				type="0"
				file_path="bt2 box1 j5-6.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="17"
			 thickness="1.0"
			 z="1.0"
			 title=""
		>
			<t2_patch
				oid="67"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 j5-7.bmp"
				links=""
				type="0"
				file_path="bt2 box1 j5-7.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="19"
			 thickness="1.0"
			 z="2.0"
			 title=""
		>
			<t2_patch
				oid="77"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k1-1.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k1-1.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="21"
			 thickness="1.0"
			 z="3.0"
			 title=""
		>
			<t2_patch
				oid="76"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k1-2.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k1-2.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="23"
			 thickness="1.0"
			 z="4.0"
			 title=""
		>
			<t2_patch
				oid="75"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k1-3.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k1-3.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="25"
			 thickness="1.0"
			 z="5.0"
			 title=""
		>
			<t2_patch
				oid="78"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k1-4.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k1-4.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="27"
			 thickness="1.0"
			 z="6.0"
			 title=""
		>
			<t2_patch
				oid="97"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k1-5.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k1-5.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="29"
			 thickness="1.0"
			 z="7.0"
			 title=""
		>
			<t2_patch
				oid="103"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k1-6.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k1-6.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="31"
			 thickness="1.0"
			 z="8.0"
			 title=""
		>
			<t2_patch
				oid="101"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k2-1.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k2-1.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="33"
			 thickness="1.0"
			 z="9.0"
			 title=""
		>
			<t2_patch
				oid="111"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k2-2.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k2-2.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="35"
			 thickness="1.0"
			 z="10.0"
			 title=""
		>
			<t2_patch
				oid="108"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k2-3.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k2-3.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="37"
			 thickness="1.0"
			 z="11.0"
			 title=""
		>
			<t2_patch
				oid="113"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k2-4.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k2-4.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="39"
			 thickness="1.0"
			 z="12.0"
			 title=""
		>
			<t2_patch
				oid="121"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k2-5.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k2-5.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="41"
			 thickness="1.0"
			 z="13.0"
			 title=""
		>
			<t2_patch
				oid="123"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k2-6.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k2-6.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="43"
			 thickness="1.0"
			 z="14.0"
			 title=""
		>
			<t2_patch
				oid="122"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k3-1.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k3-1.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="45"
			 thickness="1.0"
			 z="15.0"
			 title=""
		>
			<t2_patch
				oid="124"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k3-2.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k3-2.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="47"
			 thickness="1.0"
			 z="16.0"
			 title=""
		>
			<t2_patch
				oid="126"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k3-3.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k3-3.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="49"
			 thickness="1.0"
			 z="17.0"
			 title=""
		>
			<t2_patch
				oid="125"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k3-4.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k3-4.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="51"
			 thickness="1.0"
			 z="18.0"
			 title=""
		>
			<t2_patch
				oid="127"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k4-1.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k4-1.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="53"
			 thickness="1.0"
			 z="19.0"
			 title=""
		>
			<t2_patch
				oid="128"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k4-2.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k4-2.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="55"
			 thickness="1.0"
			 z="20.0"
			 title=""
		>
			<t2_patch
				oid="132"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k4-3.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k4-3.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="57"
			 thickness="1.0"
			 z="21.0"
			 title=""
		>
			<t2_patch
				oid="129"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k4-4.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k4-4.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="59"
			 thickness="1.0"
			 z="22.0"
			 title=""
		>
			<t2_patch
				oid="130"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k4-5.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k4-5.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="61"
			 thickness="1.0"
			 z="23.0"
			 title=""
		>
			<t2_patch
				oid="131"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k5-1.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k5-1.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="63"
			 thickness="1.0"
			 z="24.0"
			 title=""
		>
			<t2_patch
				oid="133"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k5-2.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k5-2.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="65"
			 thickness="1.0"
			 z="25.0"
			 title=""
		>
			<t2_patch
				oid="134"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k5-3.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k5-3.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="68"
			 thickness="1.0"
			 z="26.0"
			 title=""
		>
			<t2_patch
				oid="135"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k5-4.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k5-4.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="70"
			 thickness="1.0"
			 z="27.0"
			 title=""
		>
			<t2_patch
				oid="138"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k5-5.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k5-5.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="73"
			 thickness="1.0"
			 z="28.0"
			 title=""
		>
			<t2_patch
				oid="136"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt2 box1 k5-6.bmp"
				links=""
				type="0"
				file_path="bt2 box1 k5-6.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="79"
			 thickness="1.0"
			 z="29.0"
			 title=""
		>
			<t2_patch
				oid="137"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt1 bt2 box1 l1-1.bmp"
				links=""
				type="0"
				file_path="bt1 bt2 box1 l1-1.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="81"
			 thickness="1.0"
			 z="30.0"
			 title=""
		>
			<t2_patch
				oid="140"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt1 bt2 box1 l1-2.bmp"
				links=""
				type="0"
				file_path="bt1 bt2 box1 l1-2.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="83"
			 thickness="1.0"
			 z="31.0"
			 title=""
		>
			<t2_patch
				oid="139"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt1 bt2 box1 l2-1.bmp"
				links=""
				type="0"
				file_path="bt1 bt2 box1 l2-1.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="85"
			 thickness="1.0"
			 z="32.0"
			 title=""
		>
			<t2_patch
				oid="142"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt1 bt2 box1 l2-2.bmp"
				links=""
				type="0"
				file_path="bt1 bt2 box1 l2-2.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="87"
			 thickness="1.0"
			 z="33.0"
			 title=""
		>
			<t2_patch
				oid="141"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt1 bt2 box1 l2-3.bmp"
				links=""
				type="0"
				file_path="bt1 bt2 box1 l2-3.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="89"
			 thickness="1.0"
			 z="34.0"
			 title=""
		>
			<t2_patch
				oid="144"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt1 bt2 box1 l2-4.bmp"
				links=""
				type="0"
				file_path="bt1 bt2 box1 l2-4.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="91"
			 thickness="1.0"
			 z="35.0"
			 title=""
		>
			<t2_patch
				oid="143"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt1 bt2 box1 l2-5.bmp"
				links=""
				type="0"
				file_path="bt1 bt2 box1 l2-5.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="93"
			 thickness="1.0"
			 z="36.0"
			 title=""
		>
			<t2_patch
				oid="145"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt1 bt2 box1 l2-7.bmp"
				links=""
				type="0"
				file_path="bt1 bt2 box1 l2-7.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="95"
			 thickness="1.0"
			 z="37.0"
			 title=""
		>
			<t2_patch
				oid="146"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt1 bt2 box1 l3-1.bmp"
				links=""
				type="0"
				file_path="bt1 bt2 box1 l3-1.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="98"
			 thickness="1.0"
			 z="38.0"
			 title=""
		>
			<t2_patch
				oid="147"
				width="4008.0"
				height="2672.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title="bt1 bt2 box1 l3-2.bmp"
				links=""
				type="0"
				file_path="bt1 bt2 box1 l3-2.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="4008"
				o_height="2672"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="100"
			 thickness="1.0"
			 z="39.0"
			 title=""
		>
			<t2_patch
				oid="148"