<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_cat0608 [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (cat0608)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT cat0608 (rh_section3)>
	<!ATTLIST cat0608 id NMTOKEN #REQUIRED>
	<!ATTLIST cat0608 expanded NMTOKEN #REQUIRED>
	<!ELEMENT rh_section3 (local_cluster)>
	<!ATTLIST rh_section3 id NMTOKEN #REQUIRED>
	<!ATTLIST rh_section3 expanded NMTOKEN #REQUIRED>
	<!ELEMENT local_cluster (bt1)>
	<!ATTLIST local_cluster id NMTOKEN #REQUIRED>
	<!ATTLIST local_cluster expanded NMTOKEN #REQUIRED>
	<!ELEMENT bt1 (axon, ddt, synapse)>
	<!ATTLIST bt1 id NMTOKEN #REQUIRED>
	<!ATTLIST bt1 expanded NMTOKEN #REQUIRED>
	<!ELEMENT axon (area_list, synapse)>
	<!ATTLIST axon id NMTOKEN #REQUIRED>
	<!ATTLIST axon expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT synapse (profile_list)>
	<!ATTLIST synapse id NMTOKEN #REQUIRED>
	<!ATTLIST synapse expanded NMTOKEN #REQUIRED>
	<!ELEMENT profile_list (profile)>
	<!ATTLIST profile_list id NMTOKEN #REQUIRED>
	<!ATTLIST profile_list oid NMTOKEN #REQUIRED>
	<!ATTLIST profile_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT profile EMPTY>
	<!ATTLIST profile id NMTOKEN #REQUIRED>
	<!ATTLIST profile oid NMTOKEN #REQUIRED>
	<!ATTLIST profile expanded NMTOKEN #REQUIRED>
	<!ELEMENT ddt (area_list)>
	<!ATTLIST ddt id NMTOKEN #REQUIRED>
	<!ATTLIST ddt expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Project"
		unuid="1290417985236.1873492529.1249385082"
		mipmaps_folder="/../projects/kevan/DAISY/cat_0608/cat_0608_RH/reconstructions/EM/section3_local/EM/bt06/trakem2.1290417985236.1873492529.1249385082/trakem2.mipmaps/"
		storage_folder="/../projects/kevan/DAISY/cat_0608/cat_0608_RH/reconstructions/EM/section3_local/EM/bt06/"
		mipmaps_format="0"
	>
	</project>
	<t2_layer_set
		oid="16"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="2873.0"
		layer_height="3181.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_edge_confidence_boxes="true"
		prepaint="true"
	>
		<t2_calibration
			pixelWidth="1.0"
			pixelHeight="1.0"
			pixelDepth="1.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="pixel"
		/>
		<t2_layer oid="129"
			 thickness="1.0"
			 z="1.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="130"
			 thickness="1.0"
			 z="2.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="131"
			 thickness="1.0"
			 z="3.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="132"
			 thickness="1.0"
			 z="4.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="133"
			 thickness="1.0"
			 z="5.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="134"
			 thickness="1.0"
			 z="6.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="135"
			 thickness="1.0"
			 z="7.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="136"
			 thickness="1.0"
			 z="8.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="137"
			 thickness="1.0"
			 z="9.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="138"
			 thickness="1.0"
			 z="10.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="139"
			 thickness="1.0"
			 z="11.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="140"
			 thickness="1.0"
			 z="12.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="141"
			 thickness="1.0"
			 z="13.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="142"
			 thickness="1.0"
			 z="14.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="143"
			 thickness="1.0"
			 z="15.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="144"
			 thickness="1.0"
			 z="16.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="145"
			 thickness="1.0"
			 z="17.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="146"
			 thickness="1.0"
			 z="18.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="147"
			 thickness="1.0"
			 z="19.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="148"
			 thickness="1.0"
			 z="20.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="149"
			 thickness="1.0"
			 z="21.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="150"
			 thickness="1.0"
			 z="22.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="151"
			 thickness="1.0"
			 z="23.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="152"
			 thickness="1.0"
			 z="24.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="153"
			 thickness="1.0"
			 z="25.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="154"
			 thickness="1.0"
			 z="26.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="155"
			 thickness="1.0"
			 z="27.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="156"
			 thickness="1.0"
			 z="28.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="157"
			 thickness="1.0"
			 z="29.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="158"
			 thickness="1.0"
			 z="30.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="159"
			 thickness="1.0"
			 z="31.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="160"
			 thickness="1.0"
			 z="32.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="161"
			 thickness="1.0"
			 z="33.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="162"
			 thickness="1.0"
			 z="34.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="163"
			 thickness="1.0"
			 z="35.0"
			 title=""
		>
		</t2_layer>
		<t2_layer oid="164"
			 thickness="1.0"
			 z="36.0"
			 title=""
		>
			<t2_patch
				oid="240"
				width="2004.0"
				height="1336.0"
				transform="matrix(1.0,0.0,0.0,1.0,406.0,1336.0)"
				title="bt06 n3-02.bmp"
				links=""
				type="0"
				file_path="bt06 n3-02.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="165"
			 thickness="1.0"
			 z="37.0"
			 title=""
		>
			<t2_patch
				oid="239"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.998478922582901,0.05513465959910278,-0.05513465959910278,0.998478922582901,598.4721975137945,1193.5548747790162)"
				title="bt06 n3-03.bmp"
				links=""
				type="0"
				file_path="bt06 n3-03.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="166"
			 thickness="1.0"
			 z="38.0"
			 title=""
		>
			<t2_patch
				oid="238"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9943873150372501,0.10580127071657149,-0.10580127071657149,0.9943873150372501,709.731866498824,1112.878957703143)"
				title="bt06 n3-04.bmp"
				links=""
				type="0"
				file_path="bt06 n3-04.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="167"
			 thickness="1.0"
			 z="39.0"
			 title=""
		>
			<t2_patch
				oid="237"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9932260136957144,0.1161990609846656,-0.1161990609846656,0.9932260136957144,697.7234587730924,975.5611451304235)"
				title="bt06 n3-05.bmp"
				links=""
				type="0"
				file_path="bt06 n3-05.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="168"
			 thickness="1.0"
			 z="40.0"
			 title=""
		>
			<t2_patch
				oid="236"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9868620380785539,0.16156568708301863,-0.16156568708301863,0.9868620380785539,681.9594160247509,996.7372223942187)"
				title="bt06 n3-06.bmp"
				links=""
				type="0"
				file_path="bt06 n3-06.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="169"
			 thickness="1.0"
			 z="41.0"
			 title=""
		>
			<t2_patch
				oid="235"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9751091273532955,0.22172571252704676,-0.22172571252704676,0.9751091273532955,710.6966792961583,645.6963100951018)"
				title="bt06 n3-07.bmp"
				links=""
				type="0"
				file_path="bt06 n3-07.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="170"
			 thickness="1.0"
			 z="42.0"
			 title=""
		>
			<t2_patch
				oid="234"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9712418456293406,0.23809554619488799,-0.23809554619488799,0.9712418456293406,681.5676771985482,522.1083000002939)"
				title="bt06 n3-08.bmp"
				links=""
				type="0"
				file_path="bt06 n3-08.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="171"
			 thickness="1.0"
			 z="43.0"
			 title=""
		>
			<t2_patch
				oid="233"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.948286776294163,0.31741534058166343,-0.31741534058166343,0.948286776294163,632.7762006971673,282.6011361183107)"
				title="bt06 n3-09.bmp"
				links=""
				type="0"
				file_path="bt06 n3-09.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="172"
			 thickness="1.0"
			 z="44.0"
			 title=""
		>
			<t2_patch
				oid="232"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9370457691904295,0.3492071948824411,-0.3492071948824411,0.9370457691904295,657.6385503214437,242.52425401933613)"
				title="bt06 n3-10.bmp"
				links=""
				type="0"
				file_path="bt06 n3-10.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="173"
			 thickness="1.0"
			 z="45.0"
			 title=""
		>
			<t2_patch
				oid="231"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9323584692900857,0.36153593424957403,-0.36153593424957403,0.9323584692900857,564.8057147954913,194.83424466277143)"
				title="bt06 n3-11.bmp"
				links=""
				type="0"
				file_path="bt06 n3-11.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="174"
			 thickness="1.0"
			 z="46.0"
			 title=""
		>
			<t2_patch
				oid="230"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9197894595883248,0.39241314432904495,-0.39241314432904495,0.9197894595883248,577.4042227220865,190.44640456777483)"
				title="bt06 n3-12.bmp"
				links=""
				type="0"
				file_path="bt06 n3-12.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="175"
			 thickness="1.0"
			 z="47.0"
			 title=""
		>
			<t2_patch
				oid="229"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9132187753831064,0.40747057629707867,-0.40747057629707867,0.9132187753831064,560.5470756882014,-0.6103097508882911)"
				title="bt06 n3-13.bmp"
				links=""
				type="0"
				file_path="bt06 n3-13.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="176"
			 thickness="1.0"
			 z="48.0"
			 title=""
		>
			<t2_patch
				oid="228"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.8938172977636296,0.44843220658329097,-0.44843220658329097,0.8938172977636296,633.0116415886682,7.454658381286208)"
				title="bt06 n3-14.bmp"
				links=""
				type="0"
				file_path="bt06 n3-14.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="177"
			 thickness="1.0"
			 z="49.0"
			 title=""
		>
			<t2_patch
				oid="227"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9170630289026391,0.3987433929545189,-0.3987433929545189,0.9170630289026391,559.2170122601194,79.40744653339539)"
				title="bt06 n3-15.bmp"
				links=""
				type="0"
				file_path="bt06 n3-15.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="21"
			 thickness="60.0"
			 z="50.0"
			 title=""
		>
			<t2_patch
				oid="93"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9997359806757278,-0.022977278308838764,0.022977278308838764,0.9997359806757278,569.8381591839607,368.7517601393338)"
				title="bt06 n4-01.bmp"
				links=""
				type="0"
				file_path="/../projects/kevan/DAISY/cat_0608/cat_0608_RH/reconstructions/EM/section3_local/EM/bt06/bt06 n4-01.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="23"
			 thickness="60.0"
			 z="51.0"
			 title=""
		>
			<t2_patch
				oid="94"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9999324920729084,0.011621084047256383,-0.011621084047256383,0.9999324920729084,601.0992166837264,321.33443613485395)"
				title="bt06 n4-02.bmp"
				links=""
				type="0"
				file_path="/../projects/kevan/DAISY/cat_0608/cat_0608_RH/reconstructions/EM/section3_local/EM/bt06/bt06 n4-02.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="25"
			 thickness="60.0"
			 z="52.0"
			 title=""
		>
			<t2_patch
				oid="96"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9980306966815823,0.06272772488989958,-0.06272772488989958,0.9980306966815823,606.6709001319435,306.1977372080647)"
				title="bt06 n4-03.bmp"
				links=""
				type="0"
				file_path="/../projects/kevan/DAISY/cat_0608/cat_0608_RH/reconstructions/EM/section3_local/EM/bt06/bt06 n4-03.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="27"
			 thickness="60.0"
			 z="53.0"
			 title=""
		>
			<t2_patch
				oid="95"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9948280804022135,0.10157308834481123,-0.10157308834481123,0.9948280804022135,640.5439072733016,268.1655750499681)"
				title="bt06 n4-04.bmp"
				links=""
				type="0"
				file_path="/../projects/kevan/DAISY/cat_0608/cat_0608_RH/reconstructions/EM/section3_local/EM/bt06/bt06 n4-04.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="29"
			 thickness="60.0"
			 z="54.0"
			 title=""
		>
			<t2_patch
				oid="97"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9924136592477728,0.12294391733038022,-0.12294391733038022,0.9924136592477728,690.5877191495284,204.74124957805634)"
				title="bt06 n4-05.bmp"
				links=""
				type="0"
				file_path="/../projects/kevan/DAISY/cat_0608/cat_0608_RH/reconstructions/EM/section3_local/EM/bt06/bt06 n4-05.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="31"
			 thickness="60.0"
			 z="55.0"
			 title=""
		>
			<t2_patch
				oid="98"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9889163557898488,0.14847431403560335,-0.14847431403560335,0.9889163557898488,676.4913919715182,213.37065001121266)"
				title="bt06 n4-06.bmp"
				links=""
				type="0"
				file_path="/../projects/kevan/DAISY/cat_0608/cat_0608_RH/reconstructions/EM/section3_local/EM/bt06/bt06 n4-06.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="33"
			 thickness="60.0"
			 z="56.0"
			 title=""
		>
			<t2_patch
				oid="99"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9876912731421871,0.15641664209939762,-0.15641664209939762,0.9876912731421871,678.9502461028864,217.8038103165236)"
				title="bt06 n4-07.bmp"
				links=""
				type="0"
				file_path="/../projects/kevan/DAISY/cat_0608/cat_0608_RH/reconstructions/EM/section3_local/EM/bt06/bt06 n4-07.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="35"
			 thickness="60.0"
			 z="57.0"
			 title=""
		>
			<t2_patch
				oid="100"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9835900581126156,0.18041890579086928,-0.18041890579086928,0.9835900581126156,749.7440151543623,256.98566816417576)"
				title="bt06 n4-08.bmp"
				links=""
				type="0"
				file_path="/../projects/kevan/DAISY/cat_0608/cat_0608_RH/reconstructions/EM/section3_local/EM/bt06/bt06 n4-08.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="37"
			 thickness="60.0"
			 z="58.0"
			 title=""
		>
			<t2_patch
				oid="102"
				width="2004.0"
				height="1336.0"
				transform="matrix(0.9827613321513512,0.1848799026750806,-0.1848799026750806,0.9827613321513512,772.9661921153856,369.36759764125145)"
				title="bt06 n4-09.bmp"
				links=""
				type="0"
				file_path="/../projects/kevan/DAISY/cat_0608/cat_0608_RH/reconstructions/EM/section3_local/EM/bt06/bt06 n4-09.bmp"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2004"
				o_height="1336"
				min="0.0"
				max="255.0"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="39"
			 thickness="60.0"
			 z="59.0"
			 title=""
		>
			<t2_patch
				oid="101"
				width="2004.0"
				height="1336.0"