<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_c0507 [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (c0507)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT c0507 (lh)>
	<!ATTLIST c0507 id NMTOKEN #REQUIRED>
	<!ATTLIST c0507 expanded NMTOKEN #REQUIRED>
	<!ELEMENT lh (section6)>
	<!ATTLIST lh id NMTOKEN #REQUIRED>
	<!ATTLIST lh expanded NMTOKEN #REQUIRED>
	<!ELEMENT section6 (bt3)>
	<!ATTLIST section6 id NMTOKEN #REQUIRED>
	<!ATTLIST section6 expanded NMTOKEN #REQUIRED>
	<!ELEMENT bt3 (ax, ddt, myelinated_ax, asym_syn)>
	<!ATTLIST bt3 id NMTOKEN #REQUIRED>
	<!ATTLIST bt3 expanded NMTOKEN #REQUIRED>
	<!ELEMENT ax (area_list)>
	<!ATTLIST ax id NMTOKEN #REQUIRED>
	<!ATTLIST ax expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT ddt (area_list)>
	<!ATTLIST ddt id NMTOKEN #REQUIRED>
	<!ATTLIST ddt expanded NMTOKEN #REQUIRED>
	<!ELEMENT myelinated_ax (area_list)>
	<!ATTLIST myelinated_ax id NMTOKEN #REQUIRED>
	<!ATTLIST myelinated_ax expanded NMTOKEN #REQUIRED>
	<!ELEMENT asym_syn (profile_list)>
	<!ATTLIST asym_syn id NMTOKEN #REQUIRED>
	<!ATTLIST asym_syn expanded NMTOKEN #REQUIRED>
	<!ELEMENT profile_list (profile)>
	<!ATTLIST profile_list id NMTOKEN #REQUIRED>
	<!ATTLIST profile_list oid NMTOKEN #REQUIRED>
	<!ATTLIST profile_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT profile EMPTY>
	<!ATTLIST profile id NMTOKEN #REQUIRED>
	<!ATTLIST profile oid NMTOKEN #REQUIRED>
	<!ATTLIST profile expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_mode NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,ict_transform,ict_transform_list)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class NMTOKEN #REQUIRED>
	<!ATTLIST ict_transform data NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform)>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
] >

<trakem2>
	<project 
		id="0"
		title="Project"
		unuid="1246977672984.2021825951.1249385082"
		mipmaps_folder="/trakem2.1246977672984.2021825951.1249385082/trakem2.mipmaps/"
		storage_folder="/"
	>
		<c0507 id="144" expanded="true">
			<lh id="145" expanded="true">
				<section6 id="146" expanded="true">
					<bt3 id="147" expanded="true">
						<ddt id="148" expanded="true">
							<area_list id="150" oid="149">
							</area_list>
						</ddt>
						<ax id="151" expanded="true">
							<area_list id="153" oid="152">
							</area_list>
						</ax>
						<asym_syn id="154">
							<profile_list id="155" expanded="true">
								<profile id="157" oid="156">
								</profile>
								<profile id="159" oid="158">
								</profile>
								<profile id="161" oid="160">
								</profile>
								<profile id="163" oid="162">
								</profile>
								<profile id="165" oid="164">
								</profile>
								<profile id="167" oid="166">
								</profile>
							</profile_list>
						</asym_syn>
						<asym_syn id="168">
							<profile_list id="169" expanded="true">
								<profile id="171" oid="170">
								</profile>
								<profile id="173" oid="172">
								</profile>
								<profile id="175" oid="174">
								</profile>
								<profile id="177" oid="176">
								</profile>
							</profile_list>
						</asym_syn>
						<asym_syn id="178">
							<profile_list id="179" expanded="true">
								<profile id="181" oid="180">
								</profile>
								<profile id="183" oid="182">
								</profile>
								<profile id="187" oid="186">
								</profile>
								<profile id="185" oid="184">
								</profile>
								<profile id="189" oid="188">
								</profile>
								<profile id="191" oid="190">
								</profile>
							</profile_list>
						</asym_syn>
						<asym_syn id="192">
							<profile_list id="193" expanded="true">
								<profile id="195" oid="194">
								</profile>
								<profile id="197" oid="196">
								</profile>
								<profile id="199" oid="198">
								</profile>
								<profile id="201" oid="200">
								</profile>
								<profile id="203" oid="202">
								</profile>
								<profile id="205" oid="204">
								</profile>
								<profile id="207" oid="206">
								</profile>
							</profile_list>
						</asym_syn>
						<asym_syn id="208">
							<profile_list id="209" expanded="true">
								<profile id="211" oid="210">
								</profile>
								<profile id="213" oid="212">
								</profile>
								<profile id="215" oid="214">
								</profile>
								<profile id="217" oid="216">
								</profile>
							</profile_list>
						</asym_syn>
						<asym_syn id="218">
							<profile_list id="219" expanded="true">
								<profile id="221" oid="220">
								</profile>
								<profile id="223" oid="222">
								</profile>
								<profile id="225" oid="224">
								</profile>
								<profile id="227" oid="226">
								</profile>
								<profile id="229" oid="228">
								</profile>
							</profile_list>
						</asym_syn>
						<asym_syn id="230" expanded="true">
							<profile_list id="231" expanded="true">
								<profile id="233" oid="232">
								</profile>
								<profile id="235" oid="234">
								</profile>
								<profile id="237" oid="236">
								</profile>
								<profile id="239" oid="238">
								</profile>
								<profile id="241" oid="240">
								</profile>
							</profile_list>
						</asym_syn>
						<asym_syn id="242">
							<profile_list id="243" expanded="true">
								<profile id="245" oid="244">
								</profile>
								<profile id="247" oid="246">
								</profile>
								<profile id="249" oid="248">
								</profile>
								<profile id="253" oid="252">
								</profile>
								<profile id="251" oid="250">
								</profile>
								<profile id="255" oid="254">
								</profile>
								<profile id="259" oid="258">
								</profile>
								<profile id="257" oid="256">
								</profile>
								<profile id="261" oid="260">
								</profile>
								<profile id="263" oid="262">
								</profile>
							</profile_list>
						</asym_syn>
						<asym_syn id="264" expanded="true">
							<profile_list id="265" expanded="true">
								<profile id="267" oid="266">
								</profile>
								<profile id="271" oid="270">
								</profile>
								<profile id="269" oid="268">
								</profile>
								<profile id="275" oid="274">
								</profile>
								<profile id="273" oid="272">
								</profile>
								<profile id="277" oid="276">
								</profile>
								<profile id="279" oid="278">
								</profile>
								<profile id="281" oid="280">
								</profile>
							</profile_list>
						</asym_syn>
					</bt3>
				</section6>
			</lh>
		</c0507>
	</project>
	<t2_layer_set
		oid="15"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="2610.0"
		layer_height="2849.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
	>
		<t2_calibration
			pixelWidth="1.0"
			pixelHeight="1.0"
			pixelDepth="1.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="pixel"
		/>
		<t2_area_list
			oid="149"
			width="660.0"
			height="1095.0"
			transform="matrix(1.0,0.0,0.0,1.0,927.0,1036.0)"
			title="area_list"
			links="20,23,26,29,32,35,38,41,44,47,50,53,56,59,62,65,68,71,74,77,80,83,86,89,92,95,98,101,104,107,110,113,116,119,122,125,128,131,134,137,140,143"
			layer_set_id="15"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.4;fill:#b94d00;"
		>
			<t2_area layer_id="69">
				<t2_path d="M 388 304 L 388 305 L 384 305 L 384 306 L 381 306 L 381 307 L 378 307 L 378 308 L 375 308 L 375 309 L 372 309 L 372 310 L 368 310 L 368 311 L 365 311 L 365 312 L 363 312 L 363 313 L 360 313 L 360 314 L 358 314 L 358 315 L 356 315 L 356 316 L 353 316 L 353 317 L 351 317 L 351 318 L 349 318 L 349 319 L 347 319 L 347 320 L 345 320 L 345 321 L 344 321 L 344 322 L 342 322 L 342 323 L 340 323 L 340 324 L 337 324 L 337 325 L 336 325 L 336 326 L 334 326 L 334 327 L 332 327 L 332 328 L 330 328 L 330 329 L 329 329 L 329 330 L 328 330 L 328 331 L 325 331 L 325 332 L 323 332 L 323 333 L 322 333 L 322 334 L 320 334 L 320 335 L 317 335 L 317 336 L 315 336 L 315 337 L 314 337 L 314 338 L 312 338 L 312 339 L 310 339 L 310 340 L 308 340 L 308 341 L 307 341 L 307 342 L 306 342 L 306 343 L 304 343 L 304 344 L 303 344 L 303 345 L 302 345 L 302 346 L 301 346 L 301 347 L 300 347 L 300 348 L 299 348 L 299 350 L 298 350 L 298 351 L 297 351 L 297 352 L 296 352 L 296 354 L 295 354 L 295 355 L 294 355 L 294 357 L 293 357 L 293 359 L 292 359 L 292 361 L 291 361 L 291 362 L 290 362 L 290 364 L 289 364 L 289 365 L 288 365 L 288 366 L 287 366 L 287 368 L 286 368 L 286 370 L 285 370 L 285 371 L 284 371 L 284 373 L 283 373 L 283 375 L 282 375 L 282 376 L 281 376 L 281 377 L 280 377 L 280 379 L 279 379 L 279 381 L 278 381 L 278 382 L 277 382 L 277 384 L 276 384 L 276 386 L 275 386 L 275 387 L 274 387 L 274 388 L 273 388 L 273 390 L 272 390 L 272 392 L 271 392 L 271 393 L 270 393 L 270 394 L 268 394 L 268 396 L 267 396 L 267 397 L 266 397 L 266 398 L 264 398 L 264 399 L 263 399 L 263 400 L 262 400 L 262 401 L 261 401 L 261 402 L 259 402 L 259 404 L 257 404 L 257 405 L 256 405 L 256 406 L 255 406 L 255 407 L 254 407 L 254 408 L 253 408 L 253 409 L 251 409 L 251 410 L 250 410 L 250 411 L 249 411 L 249 412 L 247 412 L 247 413 L 246 413 L 246 414 L 245 414 L 245 415 L 244 415 L 244 416 L 243 416 L 243 417 L 242 417 L 242 418 L 241 418 L 241 419 L 240 419 L 240 420 L 239 420 L 239 421 L 238 421 L 238 422 L 237 422 L 237 423 L 236 423 L 236 425 L 235 425 L 235 426 L 234 426 L 234 427 L 233 427 L 233 429 L 232 429 L 232 430 L 231 430 L 231 432 L 230 432 L 230 434 L 229 434 L 229 436 L 228 436 L 228 437 L 227 437 L 227 439 L 227 440 L 226 440 L 226 442 L 226 443 L 225 443 L 225 445 L 225 446 L 224 446 L 224 448 L 224 449 L 224 450 L 223 450 L 223 452 L 223 453 L 223 454 L 223 455 L 222 455 L 222 457 L 222 458 L 222 459 L 222 460 L 222 461 L 222 462 L 222 464 L 221 464 L 221 466 L 221 467 L 221 468 L 220 468 L 220 470 L 220 471 L 220 472 L 220 473 L 220 474 L 220 475 L 220 476 L 220 478 L 219 478 L 219 480 L 219 481 L 219 482 L 219 483 L 219 484 L 218 484 L 218 486 L 218 487 L 218 488 L 217 488 L 217 490 L 217 491 L 216 491 L 216 493 L 216 494 L 215 494 L 215 496 L 215 497 L 215 498 L 214 498 L 214 499 L 213 499 L 213 501 L 213 502 L 212 502 L 212 504 L 212 505 L 211 505 L 211 507 L 211 508 L 210 508 L 210 510 L 209 510 L 209 511 L 208 511 L 208 512 L 207 512 L 207 514 L 206 514 L 206 515 L 205 515 L 205 517 L 204 517 L 204 519 L 203 519 L 203 521 L 202 521 L 202 522 L 201 522 L 201 523 L 199 523 L 199 525 L 199 526 L 198 526 L 198 527 L 197 527 L 197 528 L 196 528 L 196 529 L 195 529 L 195 531 L 194 531 L 194 532 L 193 532 L 193 534 L 192 534 L 192 535 L 191 535 L 191 536 L 190 536 L 190 538 L 189 538 L 189 539 L 188 539 L 188 540 L 187 540 L 187 542 L 185 542 L 185 544 L 183 544 L 183 546 L 182 546 L 182 547 L 181 547 L 181 548 L 180 548 L 180 549 L 179 549 L 179 550 L 178 550 L 178 551 L 177 551 L 177 552 L 176 552 L 176 553 L 175 553 L 175 554 L 174 554 L 174 555 L 173 555 L 173 556 L 172 556 L 172 557 L 171 557 L 171 559 L 170 559 L 170 561 L 169 561 L 169 563 L 169 564 L 168 564 L 168 566 L 168 567 L 168 569 L 168 570 L 168 571 L 168 572 L 169 572 L 169 574 L 170 574 L 170 576 L 172 576 L 172 578 L 173 578 L 173 580 L 174 580 L 174 582 L 176 582 L 176 584 L 177 584 L 177 585 L 178 585 L 178 586 L 179 586 L 179 587 L 180 587 L 180 588 L 181 588 L 181 590 L 183 590 L 183 592 L 183 594 L 183 595 L 183 596 L 183 597 L 183 598 L 183 599 L 183 600 L 182 600 L 182 602 L 182 603 L 182 604 L 182 605 L 182 606 L 181 606 L 181 608 L 181 609 L 181 611 L 181 613 L 181 614 L 180 614 L 180 616 L 180 618 L 180 620 L 180 622 L 179 622 L 179 624 L 179 626 L 179 628 L 179 630 L 179 632 L 179 634 L 179 636 L 179 638 L 179 640 L 179 642 L 179 644 L 179 646 L 179 648 L 179 650 L 180 650 L 180 652 L 180 654 L 180 656 L 180 657 L 181 657 L 181 659 L 181 661 L 181 663 L 181 665 L 181 666 L 182 666 L 182 668 L 182 670 L 182 672 L 183 672 L 183 674 L 184 674 L 184 675 L 185 675 L 185 677 L 186 677 L 186 678 L 188 678 L 188 679 L 190 679 L 190 680 L 195 680 L 195 681 L 198 681 L 198 682 L 200 682 L 200 683 L 201 683 L 201 684 L 203 684 L 203 685 L 206 685 L 206 686 L 207 686 L 207 687 L 210 687 L 210 688 L 214 688 L 214 689 L 218 689 L 218 688 L 224 688 L 224 687 L 225 687 L 225 686 L 232 686 L 232 687 L 235 687 L 235 688 L 236 688 L 236 689 L 237 689 L 237 690 L 238 690 L 238 691 L 239 691 L 239 692 L 240 692 L 240 693 L 241 693 L 241 694 L 246 694 L 246 693 L 249 693 L 249 692 L 251 692 L 251 690 L 253 690 L 253 689 L 255 689 L 255 688 L 260 688 L 260 689 L 266 689 L 266 690 L 272 690 L 272 691 L 275 691 L 275 690 L 279 690 L 279 689 L 284 689 L 284 688 L 291 688 L 291 687 L 299 687 L 299 686 L 303 686 L 303 685 L 306 685 L 306 684 L 309 684 L 309 683 L 311 683 L 311 682 L 313 682 L 313 681 L 316 681 L 316 680 L 317 680 L 317 679 L 320 679 L 320 678 L 322 678 L 322 677 L 324 677 L 324 676 L 326 676 L 326 675 L 329 675 L 329 674 L 331 674 L 331 673 L 333 673 L 333 672 L 334 672 L 334 671 L 336 671 L 336 670 L 337 670 L 337 669 L 339 669 L 339 668 L 341 668 L 341 667 L 342 667 L 342 666 L 343 666 L 343 665 L 345 665 L 345 664 L 347 664 L 347 663 L 349 663 L 349 662 L 350 662 L 350 661 L 351 661 L 351 660 L 352 660 L 352 659 L 353 659 L 353 658 L 354 658 L 354 657 L 356 657 L 356 656 L 357 656 L 357 654 L 358 654 L 358 653 L 360 653 L 360 652 L 361 652 L 361 650 L 363 650 L 363 649 L 364 649 L 364 647 L 365 647 L 365 646 L 366 646 L 366 645 L 366 643 L 368 643 L 368 642 L 369 642 L 369 640 L 370 640 L 370 638 L 370 637 L 371 637 L 371 636 L 372 636 L 372 635 L 373 635 L 373 634 L 373 632 L 375 632 L 375 630 L 376 630 L 376 629 L 377 629 L 377 628 L 378 628 L 378 627 L 379 627 L 379 626 L 380 626 L 380 624 L 381 624 L 381 623 L 382 623 L 382 621 L 383 621 L 383 620 L 384 620 L 384 618 L 385 618 L 385 617 L 386 617 L 386 616 L 387 616 L 387 615 L 388 615 L 388 613 L 389 613 L 389 612 L 390 612 L 390 610 L 391 610 L 391 609 L 392 609 L 392 607 L 393 607 L 393 606 L 394 606 L 394 604 L 395 604 L 395 603 L 396 603 L 396 601 L 397 601 L 397 599 L 398 599 L 398 598 L 399 598 L 399 596 L 400 596 L 400 595 L 401 595 L 401 594 L 402 594 L 402 592 L 403 592 L 403 591 L 404 591 L 404 590 L 405 590 L 405 589 L 406 589 L 406 587 L 407 587 L 407 586 L 408 586 L 408 585 L 409 585 L 409 584 L 410 584 L 410 583 L 411 583 L 411 582 L 412 582 L 412 581 L 413 581 L 413 580 L 414 580 L 414 579 L 415 579 L 415 578 L 416 578 L 416 577 L 417 577 L 417 576 L 418 576 L 418 575 L 419 575 L 419 574 L 420 574 L 420 573 L 421 573 L 421 572 L 422 572 L 422 570 L 423 570 L 423 569 L 425 569 L 425 567 L 426 567 L 426 566 L 427 566 L 427 565 L 429 565 L 429 564 L 430 564 L 430 563 L 431 563 L 431 561 L 432 561 L 432 560 L 433 560 L 433 559 L 434 559 L 434 558 L 435 558 L 435 556 L 436 556 L 436 555 L 437 555 L 437 554 L 438 554 L 438 552 L 439 552 L 439 551 L 440 551 L 440 550 L 441 550 L 441 548 L 442 548 L 442 546 L 443 546 L 443 544 L 444 544 L 444 543 L 445 543 L 445 541 L 446 541 L 446 540 L 447 540 L 447 538 L 448 538 L 448 537 L 448 535 L 449 535 L 449 534 L 450 534 L 450 532 L 452 532 L 452 531 L 453 531 L 453 530 L 454 530 L 454 529 L 455 529 L 455 527 L 456 527 L 456 525 L 456 523 L 457 523 L 457 522 L 457 520 L 457 519 L 457 517 L 456 517 L 456 516 L 456 514 L 456 512 L 456 510 L 456 508 L 457 508 L 457 507 L 457 505 L 457 503 L 458 503 L 458 501 L 458 499 L 459 499 L 459 497 L 460 497 L 460 495 L 461 495 L 461 493 L 462 493 L 462 491 L 463 491 L 463 489 L 464 489 L 464 488 L 465 488 L 465 487 L 466 487 L 466 486 L 467 486 L 467 485 L 467 483 L 468 483 L 468 482 L 469 482 L 469 480 L 471 480 L 471 479 L 472 479 L 472 478 L 473 478 L 473 476 L 474 476 L 474 475 L 475 475 L 475 474 L 476 474 L 476 472 L 477 472 L 477 471 L 478 471 L 478 469 L 479 469 L 479 468 L 480 468 L 480 467 L 481 467 L 481 466 L 482 466 L 482 465 L 483 465 L 483 464 L 484 464 L 484 462 L 485 462 L 485 461 L 486 461 L 486 460 L 487 460 L 487 459 L 487 457 L 488 457 L 488 455 L 488 453 L 489 453 L 489 452 L 489 450 L 489 448 L 489 447 L 489 445 L 488 445 L 488 444 L 488 442 L 487 442 L 487 441 L 487 439 L 487 437 L 487 436 L 487 434 L 487 432 L 487 430 L 487 428 L 488 428 L 488 427 L 488 425 L 488 423 L 489 423 L 489 421 L 490 421 L 490 419 L 490 418 L 491 418 L 491 416 L 492 416 L 492 414 L 492 412 L 491 412 L 491 410 L 490 410 L 490 409 L 490 407 L 490 405 L 490 403 L 489 403 L 489 402 L 489 400 L 488 400 L 488 398 L 487 398 L 487 396 L 487 394 L 486 394 L 486 392 L 486 390 L 485 390 L 485 388 L 485 386 L 484 386 L 484 384 L 484 382 L 483 382 L 483 380 L 483 378 L 482 378 L 482 376 L 482 374 L 481 374 L 481 373 L 481 371 L 480 371 L 480 370 L 480 368 L 479 368 L 479 366 L 478 366 L 478 364 L 477 364 L 477 362 L 476 362 L 476 360 L 475 360 L 475 359 L 474 359 L 474 357 L 473 357 L 473 356 L 473 354 L 472 354 L 472 353 L 471 353 L 471 352 L 470 352 L 470 350 L 469 350 L 469 348 L 467 348 L 467 346 L 466 346 L 466 345 L 465 345 L 465 344 L 464 344 L 464 342 L 463 342 L 463 341 L 462 341 L 462 340 L 461 340 L 461 339 L 460 339 L 460 338 L 458 338 L 458 337 L 456 337 L 456 336 L 454 336 L 454 335 L 451 335 L 451 334 L 450 334 L 450 333 L 447 333 L 447 332 L 444 332 L 444 331 L 442 331 L 442 329 L 440 329 L 440 328 L 438 328 L 438 327 L 436 327 L 436 326 L 435 326 L 435 325 L 433 325 L 433 324 L 431 324 L 431 323 L 430 323 L 430 322 L 428 322 L 428 321 L 427 321 L 427 320 L 426 320 L 426 319 L 425 319 L 425 318 L 424 318 L 424 317 L 423 317 L 423 316 L 421 316 L 421 315 L 420 315 L 420 314 L 419 314 L 419 313 L 417 313 L 417 312 L 416 312 L 416 311 L 414 311 L 414 310 L 413 310 L 413 309 L 412 309 L 412 308 L 410 308 L 410 307 L 408 307 L 408 306 L 405 306 L 405 305 L 400 305 L 400 304 z" />
			</t2_area>
			<t2_area layer_id="138">