<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_cat0608 [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (cat0608)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT cat0608 (rh_section3)>
	<!ATTLIST cat0608 id NMTOKEN #REQUIRED>
	<!ATTLIST cat0608 expanded NMTOKEN #REQUIRED>
	<!ELEMENT rh_section3 (distal_cluster)>
	<!ATTLIST rh_section3 id NMTOKEN #REQUIRED>
	<!ATTLIST rh_section3 expanded NMTOKEN #REQUIRED>
	<!ELEMENT distal_cluster (bt1)>
	<!ATTLIST distal_cluster id NMTOKEN #REQUIRED>
	<!ATTLIST distal_cluster expanded NMTOKEN #REQUIRED>
	<!ELEMENT bt1 (axon, ddt, synapse)>
	<!ATTLIST bt1 id NMTOKEN #REQUIRED>
	<!ATTLIST bt1 expanded NMTOKEN #REQUIRED>
	<!ELEMENT axon (area_list, synapse)>
	<!ATTLIST axon id NMTOKEN #REQUIRED>
	<!ATTLIST axon expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT synapse (profile_list)>
	<!ATTLIST synapse id NMTOKEN #REQUIRED>
	<!ATTLIST synapse expanded NMTOKEN #REQUIRED>
	<!ELEMENT profile_list (profile)>
	<!ATTLIST profile_list id NMTOKEN #REQUIRED>
	<!ATTLIST profile_list oid NMTOKEN #REQUIRED>
	<!ATTLIST profile_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT profile EMPTY>
	<!ATTLIST profile id NMTOKEN #REQUIRED>
	<!ATTLIST profile oid NMTOKEN #REQUIRED>
	<!ATTLIST profile expanded NMTOKEN #REQUIRED>
	<!ELEMENT ddt (area_list)>
	<!ATTLIST ddt id NMTOKEN #REQUIRED>
	<!ATTLIST ddt expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Project"
		unuid="1290168243060.928743716.1249385082"
		mipmaps_folder="trakem2.1290168243060.928743716.1249385082/trakem2.mipmaps/"
		storage_folder=""
		mipmaps_format="0"
	>
		<cat0608 id="114" expanded="true">
			<rh_section3 id="115" expanded="true">
				<distal_cluster id="116" expanded="true">
					<bt1 id="117" expanded="true">
						<ddt id="118" expanded="true">
							<area_list id="120" oid="119"/>
						</ddt>
						<ddt id="122" expanded="true">
							<area_list id="124" oid="123"/>
						</ddt>
						<axon id="125" expanded="true">
							<area_list id="127" oid="126"/>
						</axon>
						<synapse id="128" expanded="true">
							<profile_list id="129">
								<profile id="131" oid="130"/>
								<profile id="133" oid="132"/>
								<profile id="135" oid="134"/>
								<profile id="137" oid="136"/>
								<profile id="139" oid="138"/>
								<profile id="141" oid="140"/>
							</profile_list>
							<profile_list id="144">
								<profile id="146" oid="145"/>
								<profile id="148" oid="147"/>
								<profile id="150" oid="149"/>
								<profile id="152" oid="151"/>
								<profile id="158" oid="157"/>
								<profile id="154" oid="153"/>
								<profile id="156" oid="155"/>
							</profile_list>
							<profile_list id="159">
								<profile id="161" oid="160"/>
								<profile id="163" oid="162"/>
								<profile id="165" oid="164"/>
								<profile id="167" oid="166"/>
							</profile_list>
							<profile_list id="168">
								<profile id="170" oid="169"/>
								<profile id="172" oid="171"/>
								<profile id="174" oid="173"/>
								<profile id="176" oid="175"/>
								<profile id="178" oid="177"/>
							</profile_list>
							<profile_list id="179">
								<profile id="181" oid="180"/>
								<profile id="195" oid="194"/>
								<profile id="183" oid="182"/>
								<profile id="197" oid="196"/>
								<profile id="185" oid="184"/>
								<profile id="199" oid="198"/>
								<profile id="187" oid="186"/>
								<profile id="201" oid="200"/>
								<profile id="189" oid="188"/>
								<profile id="203" oid="202"/>
								<profile id="191" oid="190"/>
								<profile id="205" oid="204"/>
								<profile id="193" oid="192"/>
							</profile_list>
						</synapse>
						<synapse id="206" expanded="true">
							<profile_list id="207" expanded="true">
								<profile id="209" oid="208"/>
								<profile id="211" oid="210"/>
								<profile id="213" oid="212"/>
								<profile id="215" oid="214"/>
								<profile id="217" oid="216"/>
							</profile_list>
						</synapse>
					</bt1>
				</distal_cluster>
			</rh_section3>
		</cat0608>
	</project>
	<t2_layer_set
		oid="16"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="2898.0"
		layer_height="2003.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_edge_confidence_boxes="true"
		prepaint="true"
	>
		<t2_calibration
			pixelWidth="3.632"
			pixelHeight="3.632"
			pixelDepth="3.632"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="nm"
		/>
		<t2_area_list
			oid="119"
			width="1261.0"
			height="1031.0"
			transform="matrix(1.02652914275415,0.13398353968152066,-0.13371622100019195,1.028581327707733,1061.762433798519,463.15268201264473)"
			locked="true"
			title="area_list"
			links="45,48,57,58,59,60,61,62,63,64,65,66,67,68,69,70,75,88,89,90,92,94"
			layer_set_id="16"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.0;fill:#ff0000;"
		>
			<t2_area layer_id="71">
				<t2_path d="M 607 126 L 607 127 L 606 127 L 606 128 L 605 128 L 605 130 L 604 130 L 604 131 L 603 131 L 603 134 L 603 135 L 602 135 L 602 138 L 602 140 L 602 141 L 602 142 L 602 143 L 602 144 L 602 145 L 602 148 L 602 150 L 602 151 L 602 153 L 602 155 L 602 156 L 602 158 L 602 159 L 602 161 L 602 162 L 602 164 L 602 165 L 603 165 L 603 166 L 603 167 L 603 168 L 603 169 L 604 169 L 604 170 L 604 171 L 604 172 L 605 172 L 605 173 L 606 173 L 606 174 L 606 175 L 607 175 L 607 176 L 608 176 L 608 177 L 609 177 L 609 178 L 610 178 L 610 179 L 611 179 L 611 180 L 612 180 L 612 181 L 612 182 L 613 182 L 613 183 L 613 184 L 614 184 L 614 185 L 614 186 L 615 186 L 615 187 L 616 187 L 616 188 L 617 188 L 617 189 L 619 189 L 619 190 L 621 190 L 621 191 L 622 191 L 622 192 L 625 192 L 625 191 L 628 191 L 628 190 L 629 190 L 629 189 L 631 189 L 631 188 L 632 188 L 632 186 L 634 186 L 634 185 L 635 185 L 635 183 L 636 183 L 636 182 L 637 182 L 637 181 L 638 181 L 638 180 L 639 180 L 639 178 L 641 178 L 641 177 L 642 177 L 642 175 L 643 175 L 643 173 L 644 173 L 644 171 L 645 171 L 645 170 L 646 170 L 646 169 L 647 169 L 647 166 L 648 166 L 648 165 L 649 165 L 649 162 L 649 160 L 650 160 L 650 157 L 651 157 L 651 155 L 651 152 L 651 151 L 652 151 L 652 149 L 653 149 L 653 146 L 653 143 L 652 143 L 652 142 L 652 139 L 652 136 L 651 136 L 651 135 L 648 135 L 648 134 L 647 134 L 647 133 L 644 133 L 644 132 L 637 132 L 637 131 L 622 131 L 622 130 L 621 130 L 621 129 L 617 129 L 617 128 L 616 128 L 616 127 L 613 127 L 613 126 z" />
				<t2_path d="M 914 238 L 914 239 L 909 239 L 909 240 L 906 240 L 906 241 L 903 241 L 903 242 L 901 242 L 901 243 L 900 243 L 900 245 L 899 245 L 899 246 L 898 246 L 898 247 L 897 247 L 897 248 L 896 248 L 896 249 L 895 249 L 895 250 L 894 250 L 894 252 L 893 252 L 893 253 L 892 253 L 892 255 L 891 255 L 891 258 L 891 259 L 891 260 L 890 260 L 890 262 L 889 262 L 889 264 L 888 264 L 888 266 L 887 266 L 887 269 L 886 269 L 886 272 L 886 273 L 885 273 L 885 276 L 884 276 L 884 279 L 883 279 L 883 282 L 883 283 L 882 283 L 882 285 L 881 285 L 881 288 L 881 289 L 881 290 L 880 290 L 880 293 L 880 294 L 880 295 L 880 297 L 880 298 L 880 299 L 880 300 L 880 301 L 879 301 L 879 304 L 879 305 L 879 306 L 879 307 L 879 308 L 879 309 L 878 309 L 878 312 L 878 313 L 878 314 L 878 315 L 878 316 L 877 316 L 877 319 L 877 320 L 877 321 L 877 322 L 876 322 L 876 325 L 876 326 L 876 328 L 877 328 L 877 329 L 877 330 L 877 332 L 877 333 L 878 333 L 878 334 L 878 335 L 879 335 L 879 336 L 878 336 L 878 339 L 879 339 L 879 340 L 879 341 L 880 341 L 880 342 L 881 342 L 881 343 L 882 343 L 882 344 L 884 344 L 884 346 L 885 346 L 885 347 L 891 347 L 891 346 L 892 346 L 892 345 L 895 345 L 895 344 L 896 344 L 896 343 L 898 343 L 898 342 L 899 342 L 899 341 L 900 341 L 900 340 L 901 340 L 901 338 L 903 338 L 903 337 L 904 337 L 904 336 L 905 336 L 905 335 L 906 335 L 906 334 L 907 334 L 907 333 L 908 333 L 908 332 L 909 332 L 909 331 L 911 331 L 911 330 L 912 330 L 912 329 L 913 329 L 913 328 L 914 328 L 914 327 L 915 327 L 915 326 L 917 326 L 917 325 L 918 325 L 918 324 L 919 324 L 919 323 L 920 323 L 920 322 L 921 322 L 921 320 L 922 320 L 922 319 L 923 319 L 923 317 L 926 317 L 926 316 L 927 316 L 927 314 L 928 314 L 928 313 L 929 313 L 929 312 L 930 312 L 930 310 L 931 310 L 931 309 L 933 309 L 933 308 L 934 308 L 934 307 L 935 307 L 935 306 L 936 306 L 936 304 L 937 304 L 937 303 L 937 300 L 938 300 L 938 299 L 939 299 L 939 297 L 940 297 L 940 296 L 941 296 L 941 294 L 942 294 L 942 291 L 943 291 L 943 288 L 944 288 L 944 286 L 944 284 L 945 284 L 945 283 L 945 280 L 945 277 L 945 274 L 945 271 L 944 271 L 944 270 L 944 268 L 944 265 L 943 265 L 943 264 L 943 261 L 942 261 L 942 259 L 942 256 L 941 256 L 941 254 L 940 254 L 940 251 L 939 251 L 939 248 L 938 248 L 938 247 L 937 247 L 937 246 L 936 246 L 936 245 L 935 245 L 935 244 L 933 244 L 933 243 L 931 243 L 931 242 L 930 242 L 930 241 L 928 241 L 928 240 L 925 240 L 925 239 L 923 239 L 923 238 z" />
				<t2_path d="M 622 299 L 622 300 L 619 300 L 619 301 L 618 301 L 618 300 L 615 300 L 615 301 L 613 301 L 613 302 L 611 302 L 611 303 L 610 303 L 610 304 L 609 304 L 609 306 L 608 306 L 608 309 L 607 309 L 607 311 L 606 311 L 606 312 L 605 312 L 605 315 L 604 315 L 604 318 L 603 318 L 603 320 L 602 320 L 602 321 L 600 321 L 600 322 L 599 322 L 599 323 L 597 323 L 597 324 L 596 324 L 596 326 L 595 326 L 595 328 L 594 328 L 594 330 L 593 330 L 593 331 L 592 331 L 592 333 L 591 333 L 591 334 L 590 334 L 590 336 L 589 336 L 589 337 L 588 337 L 588 340 L 587 340 L 587 342 L 586 342 L 586 345 L 586 346 L 585 346 L 585 348 L 584 348 L 584 351 L 584 352 L 583 352 L 583 353 L 582 353 L 582 355 L 581 355 L 581 358 L 581 359 L 580 359 L 580 361 L 578 361 L 578 362 L 577 362 L 577 363 L 576 363 L 576 365 L 575 365 L 575 366 L 573 366 L 573 367 L 572 367 L 572 368 L 571 368 L 571 370 L 570 370 L 570 371 L 569 371 L 569 373 L 568 373 L 568 374 L 566 374 L 566 375 L 564 375 L 564 376 L 563 376 L 563 377 L 562 377 L 562 378 L 561 378 L 561 379 L 560 379 L 560 380 L 558 380 L 558 381 L 555 381 L 555 382 L 554 382 L 554 383 L 549 383 L 549 384 L 547 384 L 547 385 L 546 385 L 546 384 L 543 384 L 543 385 L 541 385 L 541 386 L 538 386 L 538 387 L 536 387 L 536 388 L 534 388 L 534 389 L 533 389 L 533 390 L 532 390 L 532 392 L 531 392 L 531 393 L 530 393 L 530 394 L 529 394 L 529 395 L 528 395 L 528 398 L 527 398 L 527 399 L 526 399 L 526 401 L 525 401 L 525 403 L 524 403 L 524 405 L 523 405 L 523 406 L 522 406 L 522 408 L 521 408 L 521 409 L 520 409 L 520 410 L 519 410 L 519 411 L 518 411 L 518 412 L 516 412 L 516 413 L 513 413 L 513 414 L 509 414 L 509 415 L 508 415 L 508 416 L 500 416 L 500 415 L 499 415 L 499 414 L 497 414 L 497 413 L 495 413 L 495 412 L 494 412 L 494 411 L 493 411 L 493 410 L 491 410 L 491 409 L 490 409 L 490 408 L 489 408 L 489 407 L 487 407 L 487 406 L 486 406 L 486 404 L 485 404 L 485 403 L 483 403 L 483 402 L 481 402 L 481 401 L 480 401 L 480 400 L 479 400 L 479 399 L 478 399 L 478 398 L 476 398 L 476 397 L 473 397 L 473 396 L 468 396 L 468 397 L 467 397 L 467 398 L 466 398 L 466 399 L 465 399 L 465 400 L 464 400 L 464 402 L 463 402 L 463 405 L 462 405 L 462 408 L 462 409 L 462 410 L 462 411 L 462 414 L 462 416 L 462 417 L 462 420 L 463 420 L 463 421 L 463 422 L 463 423 L 463 424 L 463 425 L 463 426 L 463 427 L 463 428 L 463 429 L 463 430 L 464 430 L 464 431 L 464 432 L 464 433 L 465 433 L 465 434 L 466 434 L 466 435 L 466 436 L 466 437 L 467 437 L 467 438 L 467 439 L 468 439 L 468 440 L 468 441 L 469 441 L 469 442 L 470 442 L 470 443 L 470 444 L 470 445 L 471 445 L 471 446 L 472 446 L 472 447 L 472 448 L 473 448 L 473 449 L 474 449 L 474 450 L 475 450 L 475 451 L 475 452 L 476 452 L 476 453 L 476 454 L 477 454 L 477 455 L 478 455 L 478 456 L 479 456 L 479 457 L 479 458 L 480 458 L 480 459 L 481 459 L 481 460 L 482 460 L 482 461 L 482 462 L 483 462 L 483 463 L 483 464 L 484 464 L 484 465 L 485 465 L 485 466 L 485 467 L 486 467 L 486 468 L 486 469 L 487 469 L 487 470 L 488 470 L 488 471 L 489 471 L 489 472 L 490 472 L 490 473 L 490 474 L 491 474 L 491 475 L 492 475 L 492 476 L 493 476 L 493 477 L 494 477 L 494 478 L 495 478 L 495 479 L 496 479 L 496 480 L 497 480 L 497 481 L 498 481 L 498 482 L 499 482 L 499 483 L 500 483 L 500 484 L 501 484 L 501 485 L 502 485 L 502 486 L 503 486 L 503 487 L 504 487 L 504 488 L 505 488 L 505 489 L 506 489 L 506 491 L 507 491 L 507 492 L 508 492 L 508 493 L 509 493 L 509 494 L 510 494 L 510 495 L 511 495 L 511 496 L 512 496 L 512 497 L 513 497 L 513 498 L 514 498 L 514 499 L 517 499 L 517 500 L 519 500 L 519 501 L 521 501 L 521 502 L 524 502 L 524 503 L 527 503 L 527 504 L 528 504 L 528 505 L 529 505 L 529 506 L 530 506 L 530 507 L 532 507 L 532 508 L 534 508 L 534 509 L 535 509 L 535 510 L 536 510 L 536 511 L 537 511 L 537 512 L 538 512 L 538 513 L 539 513 L 539 515 L 540 515 L 540 516 L 542 516 L 542 518 L 543 518 L 543 520 L 544 520 L 544 521 L 545 521 L 545 522 L 546 522 L 546 525 L 547 525 L 547 526 L 548 526 L 548 527 L 549 527 L 549 528 L 550 528 L 550 529 L 552 529 L 552 531 L 553 531 L 553 532 L 554 532 L 554 533 L 555 533 L 555 534 L 556 534 L 556 536 L 557 536 L 557 537 L 558 537 L 558 538 L 559 538 L 559 540 L 560 540 L 560 541 L 561 541 L 561 542 L 563 542 L 563 543 L 564 543 L 564 544 L 565 544 L 565 545 L 566 545 L 566 547 L 567 547 L 567 548 L 569 548 L 569 549 L 572 549 L 572 550 L 587 550 L 587 551 L 591 551 L 591 550 L 597 550 L 597 549 L 604 549 L 604 550 L 607 550 L 607 551 L 610 551 L 610 552 L 615 552 L 615 553 L 616 553 L 616 554 L 619 554 L 619 555 L 621 555 L 621 556 L 624 556 L 624 557 L 625 557 L 625 558 L 627 558 L 627 559 L 630 559 L 630 560 L 631 560 L 631 561 L 632 561 L 632 562 L 633 562 L 633 563 L 635 563 L 635 564 L 636 564 L 636 565 L 638 565 L 638 566 L 642 566 L 642 565 L 643 565 L 643 564 L 643 563 L 644 563 L 644 562 L 645 562 L 645 561 L 648 561 L 648 560 L 652 560 L 652 559 L 655 559 L 655 558 L 678 558 L 678 557 L 692 557 L 692 558 L 704 558 L 704 559 L 718 559 L 718 560 L 724 560 L 724 561 L 730 561 L 730 560 L 734 560 L 734 559 L 739 559 L 739 558 L 744 558 L 744 557 L 745 557 L 745 556 L 747 556 L 747 555 L 751 555 L 751 554 L 753 554 L 753 553 L 755 553 L 755 552 L 756 552 L 756 551 L 758 551 L 758 550 L 762 550 L 762 549 L 763 549 L 763 548 L 766 548 L 766 547 L 768 547 L 768 546 L 772 546 L 772 545 L 773 545 L 773 544 L 774 544 L 774 543 L 776 543 L 776 542 L 777 542 L 777 541 L 780 541 L 780 540 L 781 540 L 781 539 L 785 539 L 785 538 L 786 538 L 786 537 L 787 537 L 787 536 L 788 536 L 788 534 L 789 534 L 789 532 L 790 532 L 790 531 L 791 531 L 791 530 L 792 530 L 792 527 L 793 527 L 793 525 L 794 525 L 794 523 L 795 523 L 795 521 L 796 521 L 796 519 L 797 519 L 797 517 L 798 517 L 798 515 L 799 515 L 799 513 L 800 513 L 800 512 L 801 512 L 801 511 L 802 511 L 802 510 L 803 510 L 803 508 L 805 508 L 805 507 L 806 507 L 806 506 L 807 506 L 807 505 L 807 502 L 807 500 L 807 497 L 806 497 L 806 495 L 806 492 L 806 491 L 806 488 L 805 488 L 805 486 L 805 484 L 805 481 L 805 478 L 805 477 L 805 474 L 804 474 L 804 473 L 803 473 L 803 472 L 802 472 L 802 471 L 799 471 L 799 470 L 794 470 L 794 469 L 790 469 L 790 468 L 787 468 L 787 467 L 785 467 L 785 466 L 782 466 L 782 465 L 780 465 L 780 464 L 778 464 L 778 463 L 776 463 L 776 462 L 773 462 L 773 461 L 772 461 L 772 460 L 771 460 L 771 458 L 770 458 L 770 457 L 769 457 L 769 455 L 768 455 L 768 453 L 767 453 L 767 451 L 766 451 L 766 449 L 765 449 L 765 447 L 764 447 L 764 445 L 763 445 L 763 444 L 763 441 L 762 441 L 762 439 L 761 439 L 761 437 L 760 437 L 760 435 L 760 432 L 760 429 L 759 429 L 759 427 L 759 424 L 759 422 L 759 419 L 759 416 L 759 413 L 759 410 L 759 408 L 759 406 L 759 403 L 760 403 L 760 401 L 760 399 L 760 396 L 760 393 L 760 392 L 761 392 L 761 391 L 761 390 L 761 387 L 760 387 L 760 385 L 761 385 L 761 382 L 761 379 L 761 378 L 761 375 L 760 375 L 760 374 L 760 371 L 760 370 L 760 367 L 759 367 L 759 364 L 759 361 L 759 358 L 758 358 L 758 357 L 758 355 L 758 352 L 758 349 L 757 349 L 757 347 L 757 344 L 757 342 L 757 339 L 758 339 L 758 338 L 758 335 L 757 335 L 757 332 L 756 332 L 756 331 L 754 331 L 754 330 L 753 330 L 753 329 L 752 329 L 752 328 L 750 328 L 750 327 L 749 327 L 749 326 L 746 326 L 746 325 L 744 325 L 744 324 L 740 324 L 740 323 L 735 323 L 735 322 L 730 322 L 730 321 L 726 321 L 726 320 L 723 320 L 723 319 L 717 319 L 717 318 L 712 318 L 712 317 L 706 317 L 706 316 L 699 316 L 699 315 L 694 315 L 694 314 L 691 314 L 691 313 L 690 313 L 690 312 L 688 312 L 688 311 L 685 311 L 685 310 L 684 310 L 684 309 L 681 309 L 681 308 L 679 308 L 679 307 L 677 307 L 677 306 L 674 306 L 674 305 L 673 305 L 673 304 L 666 304 L 666 303 L 660 303 L 660 302 L 654 302 L 654 301 L 652 301 L 652 300 L 647 300 L 647 299 L 637 299 L 637 300 L 636 300 L 636 299 L 632 299 L 632 300 L 630 300 L 630 299 L 627 299 L 627 300 L 626 300 L 626 299 z" />